all:
	gcc -c mystring.c
	gcc -c hw0101.c
	gcc mystring.o hw0101.o -o hw0101
	gcc -c insert.c
	gcc -c hw0102.c
	gcc insert.o hw0102.o -o hw0102 -lrt
	gcc -c abacus.c -lm
	gcc -c hw0103.c
	gcc abacus.o hw0103.o -o hw0103
	gcc hw0104.c -o hw0104
	gcc -c oop.c
	gcc -c hw0105.c
	gcc oop.o hw0105.o -o hw0105
	gcc success.c -o success
