all:
	gcc -c mystring.c
	gcc -c hw0101.c
	gcc mystring.o hw0101.o -o hw0101
	gcc -c mycal.c
	gcc -c hw0102.c
	gcc mycal.o hw0102.o -o hw0102 -lm
	gcc -c mymaze.c
	gcc -c hw0104.c
	gcc mymaze.o hw0104.o -o hw0104
	gcc -c mychain.c
	gcc -c hw0103.c 
	gcc mychain.o hw0103.c -o hw0103
	gcc hw0105.c -o hw0105 -lm
